#!/bin/bash
# Quick command reference for running the GNN-SDN system

echo "╔════════════════════════════════════════════════════════════╗"
echo "║          GNN-SDN System - Command Reference               ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "Run these commands in 3 SEPARATE terminals:"
echo ""
echo "┌────────────────────────────────────────────────────────────┐"
echo "│ TERMINAL 1 - Ryu SDN Controller                           │"
echo "└────────────────────────────────────────────────────────────┘"
echo "cd /mnt/3A7069D670699981/Aravind/FinalYearProject/archive"
echo "source venv/bin/activate"
echo "python sdn/run_controller.py"
echo ""
echo "# OR use the startup script:"
echo "./sdn/start_controller.sh"
echo ""
echo "┌────────────────────────────────────────────────────────────┐"
echo "│ TERMINAL 2 - Mininet Network                              │"
echo "└────────────────────────────────────────────────────────────┘"
echo "cd /mnt/3A7069D670699981/Aravind/FinalYearProject/archive"
echo "sudo python3 sdn/iot_topology.py"
echo ""
echo "┌────────────────────────────────────────────────────────────┐"
echo "│ TERMINAL 3 - GNN Detection                                │"
echo "└────────────────────────────────────────────────────────────┘"
echo "cd /mnt/3A7069D670699981/Aravind/FinalYearProject/archive"
echo "source venv/bin/activate"
echo "python sdn/gnn_sdn_detection.py --data test_preprocessed.csv"
echo ""
echo "════════════════════════════════════════════════════════════"
echo "Testing in Mininet CLI (Terminal 2):"
echo "════════════════════════════════════════════════════════════"
echo "mininet> h3 ping h1    # Should be blocked"
echo "mininet> h1 ping h2    # Should work"
echo ""
